version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - prezagia-network

  # Opcionalmente puedes añadir una base de datos local para desarrollo
  # (Supabase ya proporciona PostgreSQL en producción)
  db-dev:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prezagia
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - prezagia-network

networks:
  prezagia-network:
    driver: bridge

volumes:
  postgres-data: